# Generated by Django 5.2.4 on 2025-07-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
