# Generated by Django 5.2.4 on 2025-07-18 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_tarefa_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='prazo',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.projeto'),
        ),
    ]
