# Generated by Django 5.2.4 on 2025-07-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_tarefa_prazo_alter_tarefa_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
