# Generated by Django 5.2.4 on 2025-07-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_tarefa_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
