# Generated by Django 5.2.4 on 2025-07-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_tarefa_prazo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
